AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
    - '**/*.gemspec'
    - 'db/Schemafile'
  Exclude:
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'lib/templates/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'
    - 'lib/generators/locale_kit.rb'
    - 'lib/generators/locale_kit/override/*.rb'
    - 'test/lib/generators/locale_kit/**/*.rb'

Style/Documentation:
  Enabled: false

Style/EmptyLines:
  Exclude:
    - '**/Gemfile'

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/Gemfile'

Style/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/Guardfile'

Style/RegexpLiteral:
  EnforcedStyle: percent_r
  AllowInnerSlashes: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Metrics/LineLength:
  Max: 240

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
  Max: 20

Metrics/AbcSize:
  Max: 35

Rails/Output:
  Exclude:
    - 'config/unicorn.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/models/**/*'
    - 'test/models/**/*'
    - 'test/factories/**/*'
